apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: staging
  labels:
    app: auth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      volumes:
        - name: ssd-1-volume
          persistentVolumeClaim:
            claimName: auth-azure-managed-disk        
      containers:
        - name: auth-api
          image: mahdihamdi99/pfa-microservices:auth
          volumeMounts: 
            - mountPath: "/data/db"
              name: ssd-1-volume
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
          - configMapRef:
              name: auth-configmap
          - secretRef:
              name: auth-secrets