apiVersion: v1
kind: Service
metadata:
  name: auth-mongo-express-svc
spec:
  type: NodePort
  selector:
    app: auth-mongo-express
  ports:
    - name: auth-mongo-express
      protocol: TCP
      port: 8081 #service port
      targetPort: 8081 #pod port
      nodePort: 30001