apiVersion: v1
kind: Service
metadata:
  name: auth-mongodb-svc
  namespace: staging
spec:
  type: ClusterIP
  selector:
    app: auth-mongodb
  ports:
    - name: auth-mongodb
      protocol: TCP
      port: 27017 #service port
      targetPort: 27017 #pod port