apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-mongodb-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-mongodb
  template:
    metadata:
      labels:
        app: appointment-mongodb
    spec:
      containers:
        - name: appointment-mongodb
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: auth-configmap
                  key: AUTH_DATABASE_NAME

            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: appointment-secrets
                  key: DATABASE_USER

            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: appointment-secrets
                  key: DATABASE_PASSWORD