apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deploy
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      volumes:
        - name: log-volume
          persistentVolumeClaim:
            claimName: rabbitmq-log-azure-managed-disk  
        - name: lib-volume
          persistentVolumeClaim:
            claimName: rabbitmq-lib-azure-managed-disk 
      containers:
        - name: rabbitmq
          image: rabbitmq:3.9.15-management-alpine
          volumeMounts:
            - mountPath: "/var/lib/rabbitmq"
              name: lib-volume 
            - mountPath: "/var/log/rabbitmq"
              name: log-volume
          ports:
            - containerPort: 5672
            - containerPort: 15672