apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
    - name: rabbitmq
      protocol: TCP
      port: 5672 #service port
      targetPort: 5672 #pod port
      # nodePort: 5672 #Node Port
    - name: rabbitmq-ui
      protocol: TCP
      port: 15672 #service port
      targetPort: 15672 #pod port
      nodePort: 30003 #Node Port