apiVersion: v1
kind: Service
metadata:
  name: api-gateway-svc
  namespace: staging
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
    - name: api-gateway
      protocol: TCP
      port: 80 #service port
      targetPort: 3000 #pod port
      nodePort: 30000 #Node Port