apiVersion: v1
kind: Service
metadata:
  name: appointment-svc
  namespace: staging
spec:
  selector:
    app: appointment-api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 3000