apiVersion: v1
kind: Service
metadata:
  name: api-gateway-svc
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - name: api-gateway
      protocol: TCP
      port: 3000 #service port
      targetPort: 3000 #pod port
      nodePort: 30000 #Node Port